name: Construir website
on:
  push: 
    branches: ["main"]
  
jobs:
    build:
      name: Construct static website
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: "1.24"
        
        - name: Build compiler
          run: |
            go mod download
            go build -o compiler .
        
        - name: Compile website
          run: |
            INPUT_DIR=./src OUTPUT_DIR=/tmp/dist ./compiler
            

        - name: Commit changes
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -B web
            git pull origin web || true
            rm -rf *
            cp -r /tmp/dist/* .
            git add -A
            git commit -m "update: $(date '+%m-%d-Y %H:%M:%S')"
        
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: web